export { TRACKS, PLANNED_TRACK_IDS, getTrack } from './config/tracks'
export { DRILLS, DRILLS_BY_ID, drillsInTrack, getDrill } from './config/curriculum'
export { averageStars, computeStars, isTrackUnlocked, TRACK_UNLOCK_STARS } from './lib/stars'
export type { StarOutcome } from './lib/stars'
export type { Drill, Stars, Track, TrackId } from './model/types'
